//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpedienteDigital.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autor()
        {
            this.AutorXActividadFortalecimiento = new HashSet<AutorXActividadFortalecimiento>();
            this.AutorXArticulo = new HashSet<AutorXArticulo>();
            this.AutorXCapitulo = new HashSet<AutorXCapitulo>();
            this.AutorXColaboracionEvento = new HashSet<AutorXColaboracionEvento>();
            this.AutorXCursoCentroCapacitacion = new HashSet<AutorXCursoCentroCapacitacion>();
            this.AutorXDesarrolloSoftware = new HashSet<AutorXDesarrolloSoftware>();
            this.AutorXObraAdministrativaDesarrollo = new HashSet<AutorXObraAdministrativaDesarrollo>();
            this.AutorXObraArtistica = new HashSet<AutorXObraArtistica>();
            this.AutorXObraDidactica = new HashSet<AutorXObraDidactica>();
            this.AutorXOrganizacionEvento = new HashSet<AutorXOrganizacionEvento>();
            this.AutorXOtraObraProfesional = new HashSet<AutorXOtraObraProfesional>();
            this.AutorXParticipacionDeportiva = new HashSet<AutorXParticipacionDeportiva>();
            this.AutorXParticipacionDestacada = new HashSet<AutorXParticipacionDestacada>();
            this.AutorXPatente = new HashSet<AutorXPatente>();
            this.AutorXPonenciaCongreso = new HashSet<AutorXPonenciaCongreso>();
            this.AutorXProyectoGraduacion = new HashSet<AutorXProyectoGraduacion>();
            this.AutorXProyectoInvestigacion = new HashSet<AutorXProyectoInvestigacion>();
            this.AutorXPublicacion = new HashSet<AutorXPublicacion>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public string correoElectronico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXActividadFortalecimiento> AutorXActividadFortalecimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXArticulo> AutorXArticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXCapitulo> AutorXCapitulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXColaboracionEvento> AutorXColaboracionEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXCursoCentroCapacitacion> AutorXCursoCentroCapacitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXDesarrolloSoftware> AutorXDesarrolloSoftware { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXObraAdministrativaDesarrollo> AutorXObraAdministrativaDesarrollo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXObraArtistica> AutorXObraArtistica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXObraDidactica> AutorXObraDidactica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXOrganizacionEvento> AutorXOrganizacionEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXOtraObraProfesional> AutorXOtraObraProfesional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXParticipacionDeportiva> AutorXParticipacionDeportiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXParticipacionDestacada> AutorXParticipacionDestacada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXPatente> AutorXPatente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXPonenciaCongreso> AutorXPonenciaCongreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXProyectoGraduacion> AutorXProyectoGraduacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXProyectoInvestigacion> AutorXProyectoInvestigacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXPublicacion> AutorXPublicacion { get; set; }
    }
}
