//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpedienteDigital.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesarrolloSoftware
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DesarrolloSoftware()
        {
            this.AutorXDesarrolloSoftware = new HashSet<AutorXDesarrolloSoftware>();
            this.DocumentoDesarrolloSoftware = new HashSet<DocumentoDesarrolloSoftware>();
            this.PersonaXDesarrolloSoftware = new HashSet<PersonaXDesarrolloSoftware>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public int numeroAutores { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXDesarrolloSoftware> AutorXDesarrolloSoftware { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoDesarrolloSoftware> DocumentoDesarrolloSoftware { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXDesarrolloSoftware> PersonaXDesarrolloSoftware { get; set; }
    }
}
