//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpedienteDigital.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModeloUtilidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModeloUtilidad()
        {
            this.DocumentoModeloUtilidad = new HashSet<DocumentoModeloUtilidad>();
            this.PersonaXModeloUtilidad = new HashSet<PersonaXModeloUtilidad>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public string tipoModelo { get; set; }
        public string innovacionDocente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoModeloUtilidad> DocumentoModeloUtilidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXModeloUtilidad> PersonaXModeloUtilidad { get; set; }
    }
}
