//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpedienteDigital.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDExpedienteDigitalMVC_ServiciosEntities : DbContext
    {
        public BDExpedienteDigitalMVC_ServiciosEntities()
            : base("name=BDExpedienteDigitalMVC_ServiciosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActividadFortalecimiento> ActividadFortalecimiento { get; set; }
        public virtual DbSet<Articulo> Articulo { get; set; }
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<AutorXActividadFortalecimiento> AutorXActividadFortalecimiento { get; set; }
        public virtual DbSet<AutorXArticulo> AutorXArticulo { get; set; }
        public virtual DbSet<AutorXCapitulo> AutorXCapitulo { get; set; }
        public virtual DbSet<AutorXColaboracionEvento> AutorXColaboracionEvento { get; set; }
        public virtual DbSet<AutorXCursoCentroCapacitacion> AutorXCursoCentroCapacitacion { get; set; }
        public virtual DbSet<AutorXDesarrolloSoftware> AutorXDesarrolloSoftware { get; set; }
        public virtual DbSet<AutorXObraAdministrativaDesarrollo> AutorXObraAdministrativaDesarrollo { get; set; }
        public virtual DbSet<AutorXObraArtistica> AutorXObraArtistica { get; set; }
        public virtual DbSet<AutorXObraDidactica> AutorXObraDidactica { get; set; }
        public virtual DbSet<AutorXOrganizacionEvento> AutorXOrganizacionEvento { get; set; }
        public virtual DbSet<AutorXOtraObraProfesional> AutorXOtraObraProfesional { get; set; }
        public virtual DbSet<AutorXParticipacionDeportiva> AutorXParticipacionDeportiva { get; set; }
        public virtual DbSet<AutorXParticipacionDestacada> AutorXParticipacionDestacada { get; set; }
        public virtual DbSet<AutorXPatente> AutorXPatente { get; set; }
        public virtual DbSet<AutorXPonenciaCongreso> AutorXPonenciaCongreso { get; set; }
        public virtual DbSet<AutorXProyectoGraduacion> AutorXProyectoGraduacion { get; set; }
        public virtual DbSet<AutorXProyectoInvestigacion> AutorXProyectoInvestigacion { get; set; }
        public virtual DbSet<AutorXPublicacion> AutorXPublicacion { get; set; }
        public virtual DbSet<CapacitacionInterna> CapacitacionInterna { get; set; }
        public virtual DbSet<CapacitacionProfesional> CapacitacionProfesional { get; set; }
        public virtual DbSet<Capitulo> Capitulo { get; set; }
        public virtual DbSet<CitaDeAtestados> CitaDeAtestados { get; set; }
        public virtual DbSet<ColaboracionEvento> ColaboracionEvento { get; set; }
        public virtual DbSet<ColaboracionExterno> ColaboracionExterno { get; set; }
        public virtual DbSet<ComisionInstitucional> ComisionInstitucional { get; set; }
        public virtual DbSet<ConocimientoSoftware> ConocimientoSoftware { get; set; }
        public virtual DbSet<CursoCentroCapacitacion> CursoCentroCapacitacion { get; set; }
        public virtual DbSet<CursoContinuo> CursoContinuo { get; set; }
        public virtual DbSet<CursoLibre> CursoLibre { get; set; }
        public virtual DbSet<CursoNoRemunerado> CursoNoRemunerado { get; set; }
        public virtual DbSet<DesarrolloSoftware> DesarrolloSoftware { get; set; }
        public virtual DbSet<Designacion> Designacion { get; set; }
        public virtual DbSet<DireccionRangoSuperior> DireccionRangoSuperior { get; set; }
        public virtual DbSet<DisenoIndustrial> DisenoIndustrial { get; set; }
        public virtual DbSet<DocumentoActividadFortalecimiento> DocumentoActividadFortalecimiento { get; set; }
        public virtual DbSet<DocumentoArticulo> DocumentoArticulo { get; set; }
        public virtual DbSet<DocumentoCapacitacionInterna> DocumentoCapacitacionInterna { get; set; }
        public virtual DbSet<DocumentoCapacitacionProfesional> DocumentoCapacitacionProfesional { get; set; }
        public virtual DbSet<DocumentoColaboracionEvento> DocumentoColaboracionEvento { get; set; }
        public virtual DbSet<DocumentoColaboracionExterno> DocumentoColaboracionExterno { get; set; }
        public virtual DbSet<DocumentoComisionInstitucional> DocumentoComisionInstitucional { get; set; }
        public virtual DbSet<DocumentoConocimientoSoftware> DocumentoConocimientoSoftware { get; set; }
        public virtual DbSet<DocumentoCursoCentroCapacitacion> DocumentoCursoCentroCapacitacion { get; set; }
        public virtual DbSet<DocumentoCursoContinuo> DocumentoCursoContinuo { get; set; }
        public virtual DbSet<DocumentoCursoLibre> DocumentoCursoLibre { get; set; }
        public virtual DbSet<DocumentoCursoNoRemunerado> DocumentoCursoNoRemunerado { get; set; }
        public virtual DbSet<DocumentoDesarrolloSoftware> DocumentoDesarrolloSoftware { get; set; }
        public virtual DbSet<DocumentoDesignacion> DocumentoDesignacion { get; set; }
        public virtual DbSet<DocumentoDireccionRangoSuperior> DocumentoDireccionRangoSuperior { get; set; }
        public virtual DbSet<DocumentoDisenoIndustrial> DocumentoDisenoIndustrial { get; set; }
        public virtual DbSet<DocumentoGradoAcademico> DocumentoGradoAcademico { get; set; }
        public virtual DbSet<DocumentoIdioma> DocumentoIdioma { get; set; }
        public virtual DbSet<DocumentoJurado> DocumentoJurado { get; set; }
        public virtual DbSet<DocumentoLibro> DocumentoLibro { get; set; }
        public virtual DbSet<DocumentoMembresiaConsejos> DocumentoMembresiaConsejos { get; set; }
        public virtual DbSet<DocumentoMembresiaOrganismos> DocumentoMembresiaOrganismos { get; set; }
        public virtual DbSet<DocumentoMiembroOrganos> DocumentoMiembroOrganos { get; set; }
        public virtual DbSet<DocumentoModeloIndustrial> DocumentoModeloIndustrial { get; set; }
        public virtual DbSet<DocumentoModeloUtilidad> DocumentoModeloUtilidad { get; set; }
        public virtual DbSet<DocumentoObraAdministrativa> DocumentoObraAdministrativa { get; set; }
        public virtual DbSet<DocumentoObraArtistica> DocumentoObraArtistica { get; set; }
        public virtual DbSet<DocumentoObraDidactica> DocumentoObraDidactica { get; set; }
        public virtual DbSet<DocumentoObtencionVegetal> DocumentoObtencionVegetal { get; set; }
        public virtual DbSet<DocumentoOrganizacionEvento> DocumentoOrganizacionEvento { get; set; }
        public virtual DbSet<DocumentoOtraObraProfesional> DocumentoOtraObraProfesional { get; set; }
        public virtual DbSet<DocumentoParticipacionAIR> DocumentoParticipacionAIR { get; set; }
        public virtual DbSet<DocumentoParticipacionComision> DocumentoParticipacionComision { get; set; }
        public virtual DbSet<DocumentoParticipacionCongreso> DocumentoParticipacionCongreso { get; set; }
        public virtual DbSet<DocumentoParticipacionDeportiva> DocumentoParticipacionDeportiva { get; set; }
        public virtual DbSet<DocumentoParticipacionDestacada> DocumentoParticipacionDestacada { get; set; }
        public virtual DbSet<DocumentoPatente> DocumentoPatente { get; set; }
        public virtual DbSet<DocumentoPonenciaCongreso> DocumentoPonenciaCongreso { get; set; }
        public virtual DbSet<DocumentoPremioNacional> DocumentoPremioNacional { get; set; }
        public virtual DbSet<DocumentoProyectoGraduacion> DocumentoProyectoGraduacion { get; set; }
        public virtual DbSet<DocumentoProyectoInvestigacion> DocumentoProyectoInvestigacion { get; set; }
        public virtual DbSet<DocumentoPublicacion> DocumentoPublicacion { get; set; }
        public virtual DbSet<DocumentoResponsableUnidad> DocumentoResponsableUnidad { get; set; }
        public virtual DbSet<DocumentoSecreto> DocumentoSecreto { get; set; }
        public virtual DbSet<DocumentoSistemaCI> DocumentoSistemaCI { get; set; }
        public virtual DbSet<DocumentoTrabajoNoRemunerado> DocumentoTrabajoNoRemunerado { get; set; }
        public virtual DbSet<GradoAcademico> GradoAcademico { get; set; }
        public virtual DbSet<Idioma> Idioma { get; set; }
        public virtual DbSet<Jurado> Jurado { get; set; }
        public virtual DbSet<Libro> Libro { get; set; }
        public virtual DbSet<MembresiaConsejos> MembresiaConsejos { get; set; }
        public virtual DbSet<MembresiaOrganismos> MembresiaOrganismos { get; set; }
        public virtual DbSet<MiembroOrganos> MiembroOrganos { get; set; }
        public virtual DbSet<ModeloIndustrial> ModeloIndustrial { get; set; }
        public virtual DbSet<ModeloUtilidad> ModeloUtilidad { get; set; }
        public virtual DbSet<ObraAdministrativaDesarrollo> ObraAdministrativaDesarrollo { get; set; }
        public virtual DbSet<ObraArtistica> ObraArtistica { get; set; }
        public virtual DbSet<ObraDidactica> ObraDidactica { get; set; }
        public virtual DbSet<ObtencionVegetal> ObtencionVegetal { get; set; }
        public virtual DbSet<OrganizacionEvento> OrganizacionEvento { get; set; }
        public virtual DbSet<OtraObraProfesional> OtraObraProfesional { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<ParticipacionAIR> ParticipacionAIR { get; set; }
        public virtual DbSet<ParticipacionComision> ParticipacionComision { get; set; }
        public virtual DbSet<ParticipacionCongreso> ParticipacionCongreso { get; set; }
        public virtual DbSet<ParticipacionDeportiva> ParticipacionDeportiva { get; set; }
        public virtual DbSet<ParticipacionDestacada> ParticipacionDestacada { get; set; }
        public virtual DbSet<Patente> Patente { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<PersonaXActividadFortalecimiento> PersonaXActividadFortalecimiento { get; set; }
        public virtual DbSet<PersonaXArticulo> PersonaXArticulo { get; set; }
        public virtual DbSet<PersonaXCapacitacionInterna> PersonaXCapacitacionInterna { get; set; }
        public virtual DbSet<PersonaXCapacitacionProfesional> PersonaXCapacitacionProfesional { get; set; }
        public virtual DbSet<PersonaXCapitulo> PersonaXCapitulo { get; set; }
        public virtual DbSet<PersonaXCita> PersonaXCita { get; set; }
        public virtual DbSet<PersonaXColaboracionEvento> PersonaXColaboracionEvento { get; set; }
        public virtual DbSet<PersonaXColaboracionExterno> PersonaXColaboracionExterno { get; set; }
        public virtual DbSet<PersonaXConocimientoSoftware> PersonaXConocimientoSoftware { get; set; }
        public virtual DbSet<PersonaXCursoCentroCapacitacion> PersonaXCursoCentroCapacitacion { get; set; }
        public virtual DbSet<PersonaXCursoContinuo> PersonaXCursoContinuo { get; set; }
        public virtual DbSet<PersonaXCursoLibre> PersonaXCursoLibre { get; set; }
        public virtual DbSet<PersonaXCursoNoRemunerado> PersonaXCursoNoRemunerado { get; set; }
        public virtual DbSet<PersonaXDesarrolloSoftware> PersonaXDesarrolloSoftware { get; set; }
        public virtual DbSet<PersonaXDesignacion> PersonaXDesignacion { get; set; }
        public virtual DbSet<PersonaXDireccionRangoSuperior> PersonaXDireccionRangoSuperior { get; set; }
        public virtual DbSet<PersonaXDisenoIndustrial> PersonaXDisenoIndustrial { get; set; }
        public virtual DbSet<PersonaXGradoAcademico> PersonaXGradoAcademico { get; set; }
        public virtual DbSet<PersonaXIdioma> PersonaXIdioma { get; set; }
        public virtual DbSet<PersonaXJurado> PersonaXJurado { get; set; }
        public virtual DbSet<PersonaXMembresiaConsejos> PersonaXMembresiaConsejos { get; set; }
        public virtual DbSet<PersonaXMembresiaOrganismos> PersonaXMembresiaOrganismos { get; set; }
        public virtual DbSet<PersonaXMiembroOrganos> PersonaXMiembroOrganos { get; set; }
        public virtual DbSet<PersonaXModeloIndustrial> PersonaXModeloIndustrial { get; set; }
        public virtual DbSet<PersonaXModeloUtilidad> PersonaXModeloUtilidad { get; set; }
        public virtual DbSet<PersonaXObraAdministrativaDesarrollo> PersonaXObraAdministrativaDesarrollo { get; set; }
        public virtual DbSet<PersonaXObraArtistica> PersonaXObraArtistica { get; set; }
        public virtual DbSet<PersonaXObraDidactica> PersonaXObraDidactica { get; set; }
        public virtual DbSet<PersonaXObtencionVegetal> PersonaXObtencionVegetal { get; set; }
        public virtual DbSet<PersonaXOrganizacionEvento> PersonaXOrganizacionEvento { get; set; }
        public virtual DbSet<PersonaXOtraObraProfesional> PersonaXOtraObraProfesional { get; set; }
        public virtual DbSet<PersonaXParticipacionAIR> PersonaXParticipacionAIR { get; set; }
        public virtual DbSet<PersonaXParticipacionComision> PersonaXParticipacionComision { get; set; }
        public virtual DbSet<PersonaXParticipacionCongreso> PersonaXParticipacionCongreso { get; set; }
        public virtual DbSet<PersonaXParticipacionDeportiva> PersonaXParticipacionDeportiva { get; set; }
        public virtual DbSet<PersonaXParticipacionDestacada> PersonaXParticipacionDestacada { get; set; }
        public virtual DbSet<PersonaXPatente> PersonaXPatente { get; set; }
        public virtual DbSet<PersonaXPonenciaCongreso> PersonaXPonenciaCongreso { get; set; }
        public virtual DbSet<PersonaXPremioNacional> PersonaXPremioNacional { get; set; }
        public virtual DbSet<PersonaXProyectoGraduacion> PersonaXProyectoGraduacion { get; set; }
        public virtual DbSet<PersonaXProyectoInvestigacion> PersonaXProyectoInvestigacion { get; set; }
        public virtual DbSet<PersonaXPublicacion> PersonaXPublicacion { get; set; }
        public virtual DbSet<PersonaXResponsableUnidad> PersonaXResponsableUnidad { get; set; }
        public virtual DbSet<PersonaXSecreto> PersonaXSecreto { get; set; }
        public virtual DbSet<PersonaXSistemaCI> PersonaXSistemaCI { get; set; }
        public virtual DbSet<PersonaXTrabajoNoRemunerado> PersonaXTrabajoNoRemunerado { get; set; }
        public virtual DbSet<PonenciaCongreso> PonenciaCongreso { get; set; }
        public virtual DbSet<PremioNacional> PremioNacional { get; set; }
        public virtual DbSet<ProyectoGraduacionGalardonado> ProyectoGraduacionGalardonado { get; set; }
        public virtual DbSet<ProyectoInvestigacion> ProyectoInvestigacion { get; set; }
        public virtual DbSet<Publicacion> Publicacion { get; set; }
        public virtual DbSet<ResponsableUnidad> ResponsableUnidad { get; set; }
        public virtual DbSet<Secreto> Secreto { get; set; }
        public virtual DbSet<SistemaCI> SistemaCI { get; set; }
        public virtual DbSet<TipoObraAdmi> TipoObraAdmi { get; set; }
        public virtual DbSet<TipoObraProfesional> TipoObraProfesional { get; set; }
        public virtual DbSet<TrabajoNoRemunerado> TrabajoNoRemunerado { get; set; }
    
        public virtual ObjectResult<pr_ObtieneConfiguracion_Result> pr_ObtieneConfiguracion(Nullable<int> idConfiguracion, ObjectParameter codigo, ObjectParameter mensaje)
        {
            var idConfiguracionParameter = idConfiguracion.HasValue ?
                new ObjectParameter("IdConfiguracion", idConfiguracion) :
                new ObjectParameter("IdConfiguracion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_ObtieneConfiguracion_Result>("pr_ObtieneConfiguracion", idConfiguracionParameter, codigo, mensaje);
        }
    }
}
