//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpedienteDigital.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizacionEvento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrganizacionEvento()
        {
            this.AutorXOrganizacionEvento = new HashSet<AutorXOrganizacionEvento>();
            this.DocumentoOrganizacionEvento = new HashSet<DocumentoOrganizacionEvento>();
            this.PersonaXOrganizacionEvento = new HashSet<PersonaXOrganizacionEvento>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public string anno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXOrganizacionEvento> AutorXOrganizacionEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoOrganizacionEvento> DocumentoOrganizacionEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXOrganizacionEvento> PersonaXOrganizacionEvento { get; set; }
    }
}
