//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpedienteDigital.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipacionDeportiva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParticipacionDeportiva()
        {
            this.AutorXParticipacionDeportiva = new HashSet<AutorXParticipacionDeportiva>();
            this.DocumentoParticipacionDeportiva = new HashSet<DocumentoParticipacionDeportiva>();
            this.PersonaXParticipacionDeportiva = new HashSet<PersonaXParticipacionDeportiva>();
        }
    
        public int ID { get; set; }
        public string nombreEvento { get; set; }
        public string nombreLugar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorXParticipacionDeportiva> AutorXParticipacionDeportiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoParticipacionDeportiva> DocumentoParticipacionDeportiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXParticipacionDeportiva> PersonaXParticipacionDeportiva { get; set; }
    }
}
