//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpedienteDigital.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaXMembresiaOrganismos
    {
        public int ID { get; set; }
        public int id_persona { get; set; }
        public int id_membresia { get; set; }
    
        public virtual MembresiaOrganismos MembresiaOrganismos { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
