//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpedienteDigital.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.PersonaXActividadFortalecimiento = new HashSet<PersonaXActividadFortalecimiento>();
            this.PersonaXArticulo = new HashSet<PersonaXArticulo>();
            this.PersonaXCapacitacionInterna = new HashSet<PersonaXCapacitacionInterna>();
            this.PersonaXCapacitacionProfesional = new HashSet<PersonaXCapacitacionProfesional>();
            this.PersonaXCapitulo = new HashSet<PersonaXCapitulo>();
            this.PersonaXCita = new HashSet<PersonaXCita>();
            this.PersonaXColaboracionEvento = new HashSet<PersonaXColaboracionEvento>();
            this.PersonaXColaboracionExterno = new HashSet<PersonaXColaboracionExterno>();
            this.PersonaXConocimientoSoftware = new HashSet<PersonaXConocimientoSoftware>();
            this.PersonaXCursoCentroCapacitacion = new HashSet<PersonaXCursoCentroCapacitacion>();
            this.PersonaXCursoContinuo = new HashSet<PersonaXCursoContinuo>();
            this.PersonaXCursoLibre = new HashSet<PersonaXCursoLibre>();
            this.PersonaXCursoNoRemunerado = new HashSet<PersonaXCursoNoRemunerado>();
            this.PersonaXDesarrolloSoftware = new HashSet<PersonaXDesarrolloSoftware>();
            this.PersonaXDesignacion = new HashSet<PersonaXDesignacion>();
            this.PersonaXDireccionRangoSuperior = new HashSet<PersonaXDireccionRangoSuperior>();
            this.PersonaXDisenoIndustrial = new HashSet<PersonaXDisenoIndustrial>();
            this.PersonaXGradoAcademico = new HashSet<PersonaXGradoAcademico>();
            this.PersonaXIdioma = new HashSet<PersonaXIdioma>();
            this.PersonaXJurado = new HashSet<PersonaXJurado>();
            this.PersonaXMembresiaConsejos = new HashSet<PersonaXMembresiaConsejos>();
            this.PersonaXMembresiaOrganismos = new HashSet<PersonaXMembresiaOrganismos>();
            this.PersonaXMiembroOrganos = new HashSet<PersonaXMiembroOrganos>();
            this.PersonaXModeloIndustrial = new HashSet<PersonaXModeloIndustrial>();
            this.PersonaXModeloUtilidad = new HashSet<PersonaXModeloUtilidad>();
            this.PersonaXObraAdministrativaDesarrollo = new HashSet<PersonaXObraAdministrativaDesarrollo>();
            this.PersonaXObraArtistica = new HashSet<PersonaXObraArtistica>();
            this.PersonaXObraDidactica = new HashSet<PersonaXObraDidactica>();
            this.PersonaXObtencionVegetal = new HashSet<PersonaXObtencionVegetal>();
            this.PersonaXOrganizacionEvento = new HashSet<PersonaXOrganizacionEvento>();
            this.PersonaXOtraObraProfesional = new HashSet<PersonaXOtraObraProfesional>();
            this.PersonaXParticipacionAIR = new HashSet<PersonaXParticipacionAIR>();
            this.PersonaXParticipacionComision = new HashSet<PersonaXParticipacionComision>();
            this.PersonaXParticipacionCongreso = new HashSet<PersonaXParticipacionCongreso>();
            this.PersonaXParticipacionDeportiva = new HashSet<PersonaXParticipacionDeportiva>();
            this.PersonaXParticipacionDestacada = new HashSet<PersonaXParticipacionDestacada>();
            this.PersonaXPatente = new HashSet<PersonaXPatente>();
            this.PersonaXPonenciaCongreso = new HashSet<PersonaXPonenciaCongreso>();
            this.PersonaXPremioNacional = new HashSet<PersonaXPremioNacional>();
            this.PersonaXProyectoGraduacion = new HashSet<PersonaXProyectoGraduacion>();
            this.PersonaXProyectoInvestigacion = new HashSet<PersonaXProyectoInvestigacion>();
            this.PersonaXPublicacion = new HashSet<PersonaXPublicacion>();
            this.PersonaXResponsableUnidad = new HashSet<PersonaXResponsableUnidad>();
            this.PersonaXSecreto = new HashSet<PersonaXSecreto>();
            this.PersonaXSistemaCI = new HashSet<PersonaXSistemaCI>();
            this.PersonaXTrabajoNoRemunerado = new HashSet<PersonaXTrabajoNoRemunerado>();
        }
    
        public int ID { get; set; }
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string categoria { get; set; }
        public int rol { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string puesto { get; set; }
        public string correoElectronico { get; set; }
        public string departamento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXActividadFortalecimiento> PersonaXActividadFortalecimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXArticulo> PersonaXArticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXCapacitacionInterna> PersonaXCapacitacionInterna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXCapacitacionProfesional> PersonaXCapacitacionProfesional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXCapitulo> PersonaXCapitulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXCita> PersonaXCita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXColaboracionEvento> PersonaXColaboracionEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXColaboracionExterno> PersonaXColaboracionExterno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXConocimientoSoftware> PersonaXConocimientoSoftware { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXCursoCentroCapacitacion> PersonaXCursoCentroCapacitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXCursoContinuo> PersonaXCursoContinuo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXCursoLibre> PersonaXCursoLibre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXCursoNoRemunerado> PersonaXCursoNoRemunerado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXDesarrolloSoftware> PersonaXDesarrolloSoftware { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXDesignacion> PersonaXDesignacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXDireccionRangoSuperior> PersonaXDireccionRangoSuperior { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXDisenoIndustrial> PersonaXDisenoIndustrial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXGradoAcademico> PersonaXGradoAcademico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXIdioma> PersonaXIdioma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXJurado> PersonaXJurado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXMembresiaConsejos> PersonaXMembresiaConsejos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXMembresiaOrganismos> PersonaXMembresiaOrganismos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXMiembroOrganos> PersonaXMiembroOrganos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXModeloIndustrial> PersonaXModeloIndustrial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXModeloUtilidad> PersonaXModeloUtilidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXObraAdministrativaDesarrollo> PersonaXObraAdministrativaDesarrollo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXObraArtistica> PersonaXObraArtistica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXObraDidactica> PersonaXObraDidactica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXObtencionVegetal> PersonaXObtencionVegetal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXOrganizacionEvento> PersonaXOrganizacionEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXOtraObraProfesional> PersonaXOtraObraProfesional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXParticipacionAIR> PersonaXParticipacionAIR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXParticipacionComision> PersonaXParticipacionComision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXParticipacionCongreso> PersonaXParticipacionCongreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXParticipacionDeportiva> PersonaXParticipacionDeportiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXParticipacionDestacada> PersonaXParticipacionDestacada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXPatente> PersonaXPatente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXPonenciaCongreso> PersonaXPonenciaCongreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXPremioNacional> PersonaXPremioNacional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXProyectoGraduacion> PersonaXProyectoGraduacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXProyectoInvestigacion> PersonaXProyectoInvestigacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXPublicacion> PersonaXPublicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXResponsableUnidad> PersonaXResponsableUnidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXSecreto> PersonaXSecreto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXSistemaCI> PersonaXSistemaCI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaXTrabajoNoRemunerado> PersonaXTrabajoNoRemunerado { get; set; }
    }
}
